### ISSUE TITLE
Phase One Iteration Plan

### ISSUE THREAD

**Issue by be5invis** [caryll/otfcc#1]
- **Dumping TrueType Tables**
   - [x] Glyph Order
   - [x] head
   - [x] hhea
   - [x] OS/2 (version 1 - 5)
   - [x] maxp (ttf only)
   - [x] name
   - [x] cmap (format 4 and 12 in Unicode encodings)
   - [x] post (version 2 and 3)
   - [x] loca, hmtx and glyf
   - [x] prep, fpgm and cvt (cvt is currently exported as bytes, instead of shorts)
   - [x] gasp
   - [x] vhea and vmtx
- **Writing TrueType Tables**
   - [x] Glyph Order
   - [x] head
   - [x] hhea
   - [x] OS/2 (version 1 - 5)
   - [x] maxp (ttf only)
   - [x] name
   - [x] cmap (format 4 and 12, for both platform 3 and 0)
   - [x] post (version 3 only)
   - [x] loca, hmtx and glyf (hmtx is not optimized yet)
   - [x] prep, fpgm and cvt
   - [x] gasp
   - [x] vhea and vmtx

**Comment by davelab6** [comment]
@be5invis is this up to date? :)

**Comment by be5invis** [comment]
@davelab6 Well it take more time than expected, but not stopped.
If you want to help me, PRs are welcome :)

**Comment by be5invis** [comment]
@clerkma @davelab6 The “old-school” TTF part is (almost) complete.
Here's an snapshot:
![](http://cd8ba0b44a15c10065fd-24461f391e20b7336331d5789078af53.r23.cf1.rackcdn.com/typeboard.vanillaforums.com/editor/js/bp7bja1yrncf.png)

**Comment by be5invis** [comment]
Since the features are moved into phase two (#2), this issue can be closed now.
