### ISSUE TITLE
Adobe Tin?

### ISSUE THREAD

**Issue by twardoch** [caryll/otfcc#2]
Does this project have any relation to [Adobe Tin](https://sourceforge.net/adobe/tintin/code/HEAD/tree/)? Adobe published a fairly complete C++ parser code in 2008-2010, under a liberal license (MIT-style I think). Is there a reason why this is better? What's the differences?

**Comment by be5invis** [comment]
Tin does not parse outline of glyphs. That's why I and @clerkma started this.

**Comment by twardoch** [comment]
I see. Perhaps you might want to borrow/adapt the CFF portions from Tin. I see that your project doesn't even mention CFF, and as we know, CFF parsing is possibly the most complex aspect of OpenType. The CFF table is quite self-contained anyway.

**Comment by be5invis** [comment]
@twardoch CFF is not in wave one, but it will be introduced later.

**Comment by be5invis** [comment]
Closed.
