### ISSUE TITLE
Mac install through brew fails

### ISSUE THREAD

**Issue by RoelN** [caryll/otfcc#29]
<img width="588" alt="1__roel_microcomputer____code_font-experiments__zsh_" src="https://cloud.githubusercontent.com/assets/4570664/18246622/3858ff92-736d-11e6-8cd1-e5cd2c463142.png">

**Comment by be5invis** [comment]
cc. @Liam0205

**Comment by Liam0205** [comment]
I'll check this later. Thanks for your report.

**Comment by Liam0205** [comment]
Hi @RoelN , this problem origins from my typo. Since otfcc has updated to version 0.3.3, this bug was fixed in the update.

You could now upgrade or install otfcc by brew with happy. : )

**Comment by RoelN** [comment]
Excellent, thanks for the fix!

<img width="731" alt="1__5_0___-__microcomputer____tmux_" src="https://cloud.githubusercontent.com/assets/4570664/18408795/333b18e4-773a-11e6-99d4-1bf5bbf27706.png">

**Comment by Liam0205** [comment]
Welcome.
