### ISSUE TITLE
Option to get relative contour values

### ISSUE THREAD

**Issue by RoelN** [caryll/otfcc#31]
In [the spec](https://www.microsoft.com/typography/OTSPEC/glyf.htm) I read about coordinates:

`First coordinates relative to (0,0); others are relative to previous point.`

Yet the coordinates dumped with otfcc all seem to be relative to (0, 0). Is there any way to dump/compile them relative to the previous point?

(This is a very similar request I did for [ttx/FontTools](https://github.com/behdad/fonttools/issues/661) if you want an example)

**Comment by be5invis** [comment]
Why do you need relative positions?
Absolute coordinates works almost everywhere.

**Comment by RoelN** [comment]
I can see I can go up to -32767 (not -32768) and 32767 as values, that's great. With relative values I could reach even more absurd glyph sizes, unless some other value (like the side bearings) is limited to a SHORT. I'm just experimenting to see how large a glyph can get!

**Comment by be5invis** [comment]
Since the internal precision has been increased to avoid rounding error when processing your font, I think this issue can be closed due to inactivity. Maybe @RoelN you can write a Node.JS script to do this, it is very simple.
