### ISSUE TITLE
otfccbuild 0.6.2 hangs while converting SourceHanSansJP and SourceHanSansKR

### ISSUE THREAD

**Issue by cwchien** [caryll/otfcc#42]
Source Han Sans 1.004
for example: [SourceHanSansJP-Regular.otf](https://github.com/adobe-fonts/source-han-sans/blob/release/SubsetOTF/JP/SourceHanSansJP-Regular.otf), [SourceHanSansKR-Regular.otf](https://github.com/adobe-fonts/source-han-sans/blob/release/SubsetOTF/KR/SourceHanSansKR-Regular.otf)
(But it's fine for **SourceHanSansCN** and **SourceHanSansTW**)

``` console
$ otfccdump -v
This is otfccdump, version 0.6.2.
$ otfccbuild -v
This is otfccbuild, version 0.6.2.
```

It hangs while using the following one-line command
``` console
$ otfccdump SourceHanSansJP-Regular.otf | otfcc-c2q | otfccbuild -o SourceHanSansJP-Regular.ttf
```

If I take the two-steps approach
``` console
$ otfccdump SourceHanSansJP-Regular.otf | otfcc-c2q > dump
(complete in reasonable time)
$ otfccbuild dump -o SourceHanSansJP-Regular.ttf
(hang and consume almost all CPU resources)
```

BTW, it's fine for all SourceHanSans while using otfcc 0.6.1

OS: Ubuntu 16.10 64bit
GCC: 6.2.0 20161005
Premake : 5.0.0-alpha10
GMake: 4.1
otfcc built with:
``` console
$ premake5 gmake
$ cd build/gmake/
$ make config=release_x64
```

**Comment by be5invis** [comment]
Have you tried to use `--verbose` when building?

**Comment by cwchien** [comment]
Sorry, I just look for something like `--debug` but not notice the `--verbose`.
Thanks for the tip! I have added it into my script.

Fix confirmed. Thank you. :)
