### ISSUE TITLE
Glyph names changing

### ISSUE THREAD

**Issue by MalcolmWooden** [caryll/otfcc#45]
When dumping a TTF the glyph for U+0009, U+000D has it's name changed to "nonmarkingreturn". This does not seem to be the case for OTF (CFF) fonts.
Would it be possible to have an option flag to preserve post tables names if a post table is present?

**Comment by moyogo** [comment]
Isn’t this FontLab Studio 5 renaming CR to nonmarkingreturn to match [standard Mac post names](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6post.html) when it generates the font?

**Comment by MalcolmWooden** [comment]
Hey Denis,  The TTF I tested definitely started life with "CR" in the post table. After going through otfccdump I noticed that the dump file has glyph name "nonmarkingreturn" where I was expecting "CR".

**Comment by be5invis** [comment]
@MalcolmWooden Did your font REALLY have a `post` table?
The naming priority in `otfccdump` for TTF fonts, when you are not using `--name-by-hash` and `--ignore-order`, is `post` > AGLFN > `uni####` > `glyph###` / `.notdef` / `.null`.

**Comment by be5invis** [comment]
@MalcolmWooden Send a file that would cause a problem please.

**Comment by MalcolmWooden** [comment]
[FontData.zip](https://github.com/caryll/otfcc/files/852974/FontData.zip)
Here is some font data for you as requested.
FullerSansLightItalic.ttf - The original TTF font data
FullerSansLightItalic.json - json file produced by otfccdump
FullerSansLightItalic_otfccbuild.ttf A TTF font from the json file created by otfccbuild
Font_Compare.xls A compare file created by our own comparison tool showing the differences.
The only flag used (appart from "-o") on json output was the "--pretty" flag.

**Comment by be5invis** [comment]
@MalcolmWooden 
Your glyph 2 is mapped into a standard Macintosh glyph name 2 (which is, `nonmarkingreturn`), in your `post` table. So otfcc's behavior is **correct**.
Closed as by-design.

**Comment by MalcolmWooden** [comment]
FYI
[Screen Shot 2017-03-19.png.zip](https://github.com/caryll/otfcc/files/853189/Screen.Shot.2017-03-19.png.zip)

**Comment by be5invis** [comment]
@MalcolmWooden otfcc is NOT designed to keep every byte unchanged after a dump-build roundtrip.
Also, ttx and OTMaster do not name your glyph `CR` either.

**Comment by MalcolmWooden** [comment]
Maybe, but I don't understand why the post table is bloated with Mac names!

**Comment by be5invis** [comment]
@MalcolmWooden You should move into another issue.
If you want to reduce file size, I recommend that you simply use `-O3` to remove `post` names.

**Comment by MalcolmWooden** [comment]
Sorry, I do not understand what you mean by "You should move into another issue" can you explain please.

**Comment by be5invis** [comment]
@MalcolmWooden 
Open another issue about that the current `post` builder produces Mac names.
