### ISSUE TITLE
'advanceWithMax' field under 'hhea' should be 'advanceWidthMax'

### ISSUE THREAD

**Issue by wutipong** [caryll/otfcc#53]
Base on the output file of version 0.9.6, under the table 'hhea', there's a field `advanceWithMax` which might be a misspelling. According to [Microsoft's opentype website](https://www.microsoft.com/typography/otspec/hhea.htm) and [Apple's ](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6hhea.html), the field should be `advanceWidthMax`.

**Comment by be5invis** [comment]
Fixed in `poly` branch.
