### ISSUE TITLE
Cannot properly dump transformation matrix in U+1D1D in Noto Sans

### ISSUE THREAD

**Issue by CyanoHao** [caryll/otfcc#56]
This is original U+1D1D in Noto Sans:
![screenshot 34](https://user-images.githubusercontent.com/14287996/49778019-03e5ed80-fd3e-11e8-881f-98f224cf03e9.png)

After running
```
otfccdump.exe NotoSans-Regular.ttf | otfccbuild.exe -o a.ttf
```
it looks like this:
![screenshot 33](https://user-images.githubusercontent.com/14287996/49778030-195b1780-fd3e-11e8-93aa-d188660b3f3c.png)

`otfccdump` dumps U+1D1D in Noto Sans to this:
```json
        "uni1D1D": {
            "advanceWidth": 618,
            "references": [
                {"glyph":"n","x":38,"y":584,"a":0,"b":-1,"c":1,"d":-1,"roundToGrid":true}
            ],
            "instructions": ["PUSHB_2",0,1,"PUSHW_1",584,"PUSHB_1",51,"CALL"]
        },
```
It seems that `"d"` should be `0`.

[NotoSans-Regular.zip](https://github.com/caryll/otfcc/files/2665913/NotoSans-Regular.zip)
otfcc version: 0.10.3 (prebuilt Windows x64, downloaded from https://github.com/caryll/otfcc/releases/tag/v0.10.3-alpha)

**Comment by be5invis** [comment]
I made a fix in master. You can try to rebuild it on your own.
OTFCC is now in a maintenance mode (I have a TypeScript project internally in MSFT does the same thing).
