### ISSUE TITLE
Phase 3, CFF

### ISSUE THREAD

**Issue by be5invis** [caryll/otfcc#6]
In this phase, otfcc will be able to read and write CFF outlines.

The CFF table data will be separated into two records:

* The existing `glyf` for curves;
* A new record `CFF_` for metadata.

 * [x] CFF Parser
    - [x] Metadata
    - [x] Outline & Metrics
    - [x] Hints
    - [x] CID
 * [x] CFF Writer
    - [x] Metadata
    - [x] Outline & Metrics
    - [x] Hints
    - [x] CID
 * [x] JSON format integration

**Comment by be5invis** [comment]
Mostly done.

**Comment by anthrotype** [comment]
Good job! 👍

**Comment by be5invis** [comment]
@anthrotype It still need optimizations, see #16.
For example, @kenlunde’s SHS increased about 4MB after a dump-build cycle.

**Comment by anthrotype** [comment]
not sure it's relevant here, but have you had a look at [compreffor](https://github.com/googlei18n/compreffor)?

**Comment by be5invis** [comment]
@anthrotype What does this library manipulate, entire SFNT or only CFF table?
*otfcc* is written in C, therefore I need to convert their interface.

**Comment by be5invis** [comment]
ps. @anthrotype I think we can move the discussions to #16.
